name: DataUpdate

on:
  schedule:
    - cron:  '0 8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
            python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy
          pip install matplotlib
          pip install requests
      
      - name: Update data
        run: |
            python case-scenarios.py
            python case-display.py
            python case-2d-view.py

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Daily Data Update
        
      - name: Done
        run: echo Done
